package com.qemumanager.util;

import com.qemumanager.model.VMConfig;
import org.json.JSONObject;
import java.io.*;
import java.util.ArrayList;
import java.util.List;

public class VMConfigIO {

    public static boolean save(VMConfig vm) {
        try {
            File dir = new File(vm.vmDir);
            if (!dir.exists()) {
                boolean created = dir.mkdirs();
                if (!created && !dir.exists()) {
                    return false;
                }
            }
            File f = new File(dir, "vm.json");
            FileWriter fw = new FileWriter(f);
            fw.write(vm.toJson().toString(2));
            fw.flush();
            fw.close();
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    public static String saveWithError(VMConfig vm) {
        try {
            File dir = new File(vm.vmDir);
            if (!dir.exists()) {
                boolean created = dir.mkdirs();
                if (!created && !dir.exists()) {
                    return "Failed to create directory: " + vm.vmDir;
                }
            }
            File f = new File(dir, "vm.json");
            FileWriter fw = new FileWriter(f);
            fw.write(vm.toJson().toString(2));
            fw.flush();
            fw.close();
            return null; // success
        } catch (Exception e) {
            return e.getMessage();
        }
    }

    public static VMConfig load(String vmDir) {
        try {
            File f = new File(vmDir, "vm.json");
            if (!f.exists()) return null;
            BufferedReader br = new BufferedReader(new FileReader(f));
            StringBuilder sb = new StringBuilder();
            String line;
            while ((line = br.readLine()) != null) sb.append(line);
            br.close();
            return VMConfig.fromJson(new JSONObject(sb.toString()));
        } catch (Exception e) {
            return null;
        }
    }

    public static List<VMConfig> loadAll(String baseDir) {
        List<VMConfig> list = new ArrayList<>();
        try {
            File base = new File(baseDir);
            if (!base.exists()) {
                base.mkdirs();
                return list;
            }
            File[] dirs = base.listFiles((File f) -> f.isDirectory());
            if (dirs == null) return list;
            for (File d : dirs) {
                VMConfig vm = load(d.getAbsolutePath());
                if (vm != null) list.add(vm);
            }
        } catch (Exception e) {
            // Return empty list on any error
        }
        return list;
    }

    public static boolean writeStartScript(VMConfig vm) {
        try {
            File f = new File(vm.vmDir, "start.sh");
            FileWriter fw = new FileWriter(f);
            fw.write("#!/bin/bash\n# Generated by qemu-manager-android\n# VM: " + vm.name + "\n\n");
            fw.write(CommandBuilder.formatCommand(vm) + "\n");
            fw.flush();
            fw.close();
            f.setExecutable(true);
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    // Alias for compatibility
    public static boolean saveConfig(VMConfig vm) { return save(vm); }
}
